{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
